Repository altertek/attestation-covid19, pull requests merged in 2020-04, with the labels that each got.

#29 fix: service-worker cache
  package-lock.json
  package.json
  src/index.html
  src/sw.js
Labels: bug

#30 fix: set the correct autocomplete values
  src/index.html
Labels: bug

#31 Feature/improve lighthouse scoring
  src/index.html
Labels: bug, enhancement

#33 feat: Add autoslash in birthdate field
  src/certificate.js
Labels: enhancement

#36 feat: Add basic footer
  src/index.html
Labels: enhancement

#39 docs: fix indentation in readme
  README.md
Labels: documentation

#37 feat: Add subresource integrity plugin
  package-lock.json
  package.json
Labels: enhancement
